# Generated by Django 3.2.5 on 2021-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210714_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='media/images/categories/'),
            preserve_default=False,
        ),
    ]
